# Generated by Django 4.0.1 on 2022-02-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_remove_useraccount_username")]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="telephone_number")
    ]
