# Generated by Django 4.0.2 on 2022-02-16 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "last_updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("zemlja_porekla", models.CharField(max_length=32)),
                ("picture", models.ImageField(upload_to=None)),
                ("oblast_predavanja", models.CharField(max_length=32)),
            ],
            options={"ordering": ("created_on",), "abstract": False},
        )
    ]
