# Generated by Django 4.0.2 on 2022-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tutors", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="picture",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="media/",
                verbose_name="Document",
            ),
        )
    ]
