# Generated by Django 4.0.2 on 2022-02-17 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("tutors", "0002_alter_tutor_picture")]

    operations = [
        migrations.RemoveField(model_name="tutor", name="oblast_predavanja"),
        migrations.RemoveField(model_name="tutor", name="zemlja_porekla"),
        migrations.AddField(
            model_name="tutor",
            name="country_of_origin",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="current_situation",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tutor", name="hourly_rate", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="tutor",
            name="languages_spoken",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="subject_taught",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="teaching_experience",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="picture",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="media/",
                verbose_name="Slika",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "last_updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("subject", models.CharField(max_length=32, null=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="tutors.tutor",
                    ),
                ),
            ],
            options={"ordering": ("created_on",), "abstract": False},
        ),
    ]
