# Generated by Django 4.0.2 on 2022-02-17 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0004_certificate_certificate_certificate_description_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="media/",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="picture",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="media/",
                verbose_name="picture",
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "last_updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("university", models.CharField(max_length=32, null=True)),
                ("degree", models.CharField(max_length=32, null=True)),
                ("degree_type", models.CharField(max_length=300, null=True)),
                ("specialization", models.CharField(max_length=32, null=True)),
                ("years_of_study", models.CharField(max_length=9, null=True)),
                (
                    "diploma",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="media/",
                        verbose_name="diploma",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="tutors.tutor",
                    ),
                ),
            ],
            options={"ordering": ("created_on",), "abstract": False},
        ),
    ]
