# Generated by Django 4.0.2 on 2022-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0005_certificate_document_alter_tutor_picture_education")
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="headline",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="introduce",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="methodology",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
