name: Deploy main

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/nauci-api
          command: |
            sudo git pull origin main
            sudo pip3 install -r requirements.txt
            python3 manage.py makemigrations
            python3 manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          comment: Deploy the main branch

      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"